### ISSUE TITLE
Read and write tibbles

### ISSUE THREAD

**Issue by hadley** [rstats-db/odbconnect#3]

**Comment by joranE** [comment]
I realize that development here is still very early, but am I to gather that the intent here is that queries in odbconnect will return tibbles rather than data frames to the user by default? (I don't know what it would mean to write tibbles to a db...)

That would seem like an odd departure from all the other general R db connectivity packages (RSQLite, RMySQL, etc.), so maybe I'm just misunderstanding something.

**Comment by jimhester** [comment]
Yes that is the intent, tibbles are also regular `data.frames`, so if you do not have the tibble library attached they will work like any other data frame.

**Comment by bbolker** [comment]
In contrast, if the tibble <s>library</s>package *is* attached, the differences between tibbles and data frames can occasionally lead to surprises. I can't reconstruct the example at the moment, but I encountered some code deep within `MCMCglmm` that assumed `x[,"single_column_name"]` would be a vector, which is not true of tibbles, and which broke in a surprising/obscure way. (I haven't gotten around to suggesting to the package maintainer that they change it to `x[["single_column_name"]]`, which is defensive ...) If it doesn't clutter the design too much, perhaps follow `data.table::fread` in adding a `data.frame=` argument (in `data.table` it's `data.table=getOption("datatable.fread.datatable")`. At the very least, this would highlight the issue for attentive users ...

**Comment by joranE** [comment]
My argument would boil down to:

1. tibbles are _not_ "just" data frames; they do behave subtly differently in a small number of rare cases that can be very confusing if you're not expecting it.
2. General purpose database connectivity packages should be as consistent as possible with the whole ecosystem of such packages. That's what I like about the rethinking of the DBI interface. I presume there are no plans to have RSQLite, RMySQL, RPostgreSQL, etc (let alone RODBC) start returning tibbles. As such, a new ODBC package should follow that convention and just return data frames.

**Comment by bbolker** [comment]
Out of curiosity, and not necessarily on-topic here: what would be a good way to automatically test a large corpus of R code to see what bits broke when you tried to substitute tibbles for data frames?

**Comment by carlganz** [comment]
Small comment related to @bbolker: there are quite a few (easily reproducible) examples where tibble breaks the `survey` package for the reason Ben mentioned.

**Comment by eddelbuettel** [comment]
FWIW in a [public] package of ours we use an optional argument `returnAs=c("xts", "data.table")` to now optionally select away from the historic default. I use the same pattern for work other data getters which return (also as `xts` and now optionally as `data.table()`.

You could *easily* do the same here, and even do one better via, say,

       returnAs = c(getValue("returnAsDefault"), "data.frame"))

where `getValue()` queries a package environment filled at package load, and/or an `options()` value, and/or an environment variable -- as you see fit -- and `data.frame` provides a fallback.

That would a polite way to go about it, rather than forcing a data type down on people, our warning's notwithstanding.

**Comment by hadley** [comment]
I think making an option to control the return type is the worst of possible options — stringsAsFactors anyone? I'm also not a big fan of making the return type of a function contingent on one of the options. Maybe you could persuade me that odbconnect should just return a regular data frame, but I'm of the opinion that downstream problems with tibbles are largely a short term problem. IMO it forces package authors to fix code that could currently be silently returning incorrect results (because of the partial match performed by `[`).

Packages that provide tibbles now always import tibble so that the behaviour is consistent, and not dependent on whether or not you have attached tibble yourself.

**Comment by bbolker** [comment]
I'm not saying this is easy (if I were starting from scratch I imagine I would make the same choices you've made about tibble behaviour), but, grumbling about `drop=TRUE` notwithstanding, expecting e.g. `x[,1]` to return an atomic type is pretty deeply embedded in the R idiom; unlike e.g. using `$` instead of `[[`, I don't think I've ever seen someone suggest that it's bad practice.

Also, re: partial matching: `?"["` says:

> Unlike S (Becker _et al_ p. 358)), R never uses partial matching when extracting by ‘[’ ...

I'm a little confused.  Can you give an example of the partial-matching use case/pitfall you're thinking of?

**Comment by hadley** [comment]
Oh I guess `[` doesn't do partial matching, my mistake. I'm pretty sure there is some silent mistake that tibble protect you from, but maybe I'm misremembering that it's related to `[`.

(We did break `$` briefly but quickly determined that throwing an error if the column didn't exist broke too much existing code).

**Comment by jimhester** [comment]
If there are packages that break when using tibbles that you are not able or willing to fix the solution is simple.
```r
class(x) <- "data.frame"
```
tibbles have _exactly_ the same underlying data as a normal data.frame, they just have the additional classes, so just remove them if there are downstream issues. FWIW this is literally all `tibble:::as.data.frame.tbl_df` does.

**Comment by eddelbuettel** [comment]
@jimhester We understand the coding.  We just find it that that this team is deliberate in letting things break, and forcing this change onto users.  That is simply the wrong design.

We are trying to explain to you and other that _in light of demonstrated breakage downstream_ it is not a good idea change the return type to a package barely a year old.   

Production setups, reproducible workflows, and a userbase of R now measuring in millions deserve better.

**Comment by hadley** [comment]
@eddelbuettel no one is forcing you to use odbconnect - it's not even on CRAN! I really don't understand how changing a package that no one uses (because it only just started working) can possibly be construed as forcing changes downstream. If you don't like odbconnect, you can continue to use RJDBC or RODBC.

**Comment by eddelbuettel** [comment]
Because it has _you_ and your somewhat messianic zeal of forcing everybody to do things the way you deeming to be the only acceptable one.   You have both the platform and visibility to affect a lot of people

And I find it really aggravating that you seem unable to appreciate the very simple fact that choice would be a good thing.  Or do understand the value of conforming to established standard.

But you and I had these discussions for years, and I don't expect you to all of a sudden come around.  This is a lost cause, and that is really more than twice as sad because of the impact you have.  End of thread for me.   I shouldn't have let myself be dragged over here.   Unsub'ed.

**Comment by bbolker** [comment]
If I can chime in with a more moderate view (now that Dirk has left the building) ... All I'm suggesting is that it would be a nice gesture, and would add a very small amount of overhead, to add a `tibble=` argument (that could be `TRUE` by default) to allow users to set `tibble=FALSE` to get a data frame rather than a tibble returned (or `returnAs=c("tibble","data.frame")`).  I know this adds complexity (although not much) and violates a software engineering principle ("always return the same type"), and I know that users could do this themselves after the fact via `as.data.frame()`, but I really think it would be a good idea. (As @joranE points out, it would be improving consistency with the rest of the DBI ecosystem.) Otherwise, if and when this package becomes popular, you will in practice be pushing tibble-compliance on downstream code maintainers who have to respond to users wondering why the code doesn't work any more ...

**Comment by gavinsimpson** [comment]
> Otherwise, if and when this package becomes popular, you will in practice be pushing tibble-compliance on downstream code maintainers who have to respond to users wondering why the code doesn't work any more ... @bbolker 

Wouldn't you just tell those users to file a bug report here?

Returning something whose type is conditional on an argument is kind of anathema to @hadley's R-worldview and I get that. So my reading of this issue is that it should have come down to a decision whether to return a `data.frame` *or* a `tibble`. I can see why @hadley and @jimhester went with tibbles, but I feel it is a misstep. You guys are welcome to write whatever code you want, of course, but, when you choose to do something different to the *n* other packages in this dbi-focused repo, it comes across as, unfortunately, dogmatic. Optics wise, this sucks, because you're doing it here, not in say the Rstudio repo or somesuch.

By the same token of simplicity, you could have chosen to return a `data.frame` and then just have users use the `as.tibble()` method (or whatever it is called) to achieve what you want whilst not riding roughshod over preexisting conventions.

Saying "you don't have to use it" is largely a cop out; given your standing within the community, @hadley, undoubtedly people will use this, claim it to be the best thing since sliced bread (probably for good reason), and some fraction will complain bitterly that everything else sucks or is broken.

**Comment by joranE** [comment]
So I also want to re-iterate that I didn't intend for this discussion to get contentious.

First, I freely and gladly acknowledge that odbconnect is your package and so you are quite obviously free to do what you want with it. I simply feel fairly strongly that a package *like* odbconnect, i.e. a general purpose db connectivity package, really belongs more in the "base R" ecosystem than the "tidyverse" ecosystem.

Because of that, it seems preferable to me that it behave like all the other db packages, and any inconvenience that comes from wanting to have them use tibbles within the tidyverse world should be borne by the tidyverse packages/users, not generic packages/users.

So I just wanted to provide that data point of feedback, but I'm not going to harp on it any further, and will remain interested in this ongoing development of the package regardless of the direction you take.

**Comment by hadley** [comment]
I still think that overall returning a data frame is _more_ user hostile than returning a tibble because of the print method. You print a data frame many times; you run in to tibble compatibilities rarely (as evidenced by people who are largely using readr etc without difficulties). 

I push tibbles because I genuinely believe that overall they provide a better experience for most users. Yes, there will be small issues here and there, but there don't appear to be widespread problems today, and they will get rarer and rarer as package authors adjust. I would rather introduce a little work in the short term in order to provide a much safer data frame interface in the long term.

**Comment by gavinsimpson** [comment]
@hadley you assume package authors will just conform. Until such a time as I don't need dplyr to do stuff that should be in tibble, and I can use your tibble-using pkg stack end to end without missing functionality (aka bugs), which cause me to tibble -> df -> tibble, I'm not going to release a package that uses it to CRAN. And that's from someone who really likes tibbles. The system just isn't mature enough yet for most package authors to jump on board.

Also, you're assuming an awful lot as to the motivations of many package developers. Do you honestly think that everyone is going to change to tibbles? Unless you get tibble in base R, I doubt that'll ever happen. So isn't the responsible thing to not wed tools to tibbles against convention given the triviality of coercing an object to a tibble? Your suggestion assumes we're already in some future R 4.x land where the tibbles won, and we're not.

I don't disagree that the situation might be better with tibble or tibble-like consistency in base R, but unless you convince everyone to change the other dbi-related packages (not to mention lots of other code) the suggestion to use tibbles is not, as you say just "short term" pain but something that will endure for as long as people believe more in backwards compatibility than you do.

**Comment by hadley** [comment]
Some concrete examples of where tribbles are causing problems would be hopeful. Obviously I have a lot of packages producing tibbles already in the wild and I'm not seeing a lot of complaints. What am I missing?

Every day I see examples of data frames causing problems by coercing strings to factors, and I am sure there are many other errors that are going silently undetected because of the permissive nature of data frames. 

Also I don't think any one will retrofit old packages to use [[ instead of [ unless there is some win (i.e. tibble support). 

But overall there is some mismatch in our perceptions of R users. I see a lot of people with bugs due to data frames and few due to tibbles. And I don't understand why the occasional explicit coercion to a data frame is a problem.

**Comment by bbolker** [comment]
For what it's worth:

```
library(MCMCglmm)
library(tibble)
## from ?MCMCglmm:
data(PlodiaPO)  
model1 <- MCMCglmm(PO~1, random=~FSfamily, data=PlodiaPO, verbose=FALSE)
pp <- as_tibble(PlodiaPO)
model2 <- MCMCglmm(PO~1, random=~FSfamily, data=pp,verbose=FALSE)
## Warning messages:
## 1: Unknown column 'family' 
## 2: Setting row names on a tibble is deprecated. 
## 3: Unknown column 'MCMC_dummy' 
## 4: Unknown column 'MCMC_dummy' 
```

The results don't look substantively different (I think the actual error I got when I was doing some work with MCMCglmm was further downstream), but the warning messages are worrying.

**Comment by hadley** [comment]
I think it's bad practice because you should use `[` for selecting multiple elements and `[[` for selecting a single element - this is a strong principle that generalises to all data structures (and to subset-assignment). In package code, I'd also argue that using `df[, var]` leads to more problems overall because it's easy to forget that it might return a data frame or a vector.

I think we all agree that tibbles are going to cause more problems with package code in the short term. I think where we disagree are the short term benefits of the change (i.e. is the trade-off for enhanced printing and stricter subsetting worth it?), and how long until we see the the long-term benefits of the change (i.e. how long until many users are protected against accidental coercion of factors and partial matching bugs).

**Comment by bbolker** [comment]
PS "Some concrete examples of where tribbles are causing problems" ... https://www.youtube.com/watch?v=Bprgl_4z6gY  (sorry)

**Comment by hadley** [comment]
We've decided to focus on DBI compatibility for the short-term, so we won't return tibbles. We'll probably reconsider in a year or two.

**Comment by eddelbuettel** [comment]
Bravo.  The right call in the short term.  

For the longer term, we shall; and for the transition I reiterate my initial suggestion of providing _an option_ to users.  Letting users decide, rather than dictating terms, is the right call.
